### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by kermitdafrog8** [GrammaTech/gtirb-pprinter#10]
Consolidate compiler generated dependencies of target gtirb_layout
[  4%] Building CXX object src/gtirb_layout/CMakeFiles/gtirb_layout.dir/gtirb_layout.cpp.o
/opt/gtirb-pprinter-1.6.0/src/gtirb_layout/gtirb_layout.cpp: In function ‘bool gtirb_layout::layoutRequired(gtirb::Module&)’:
/opt/gtirb-pprinter-1.6.0/src/gtirb_layout/gtirb_layout.cpp:88:12: error: ‘class gtirb::Module’ has no member named ‘getAddress’
   88 |     if (!M.getAddress()) {
      |            ^~~~~~~~~~
make[2]: *** [src/gtirb_layout/CMakeFiles/gtirb_layout.dir/build.make:76: src/gtirb_layout/CMakeFiles/gtirb_layout.dir/gtirb_layout.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:286: src/gtirb_layout/CMakeFiles/gtirb_layout.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by kermitdafrog8** [comment]
I have other issues after this when I do make -j4.  This output is just with a single make job.

**Comment by jdorn-gt** [comment]
It looks like you're building gtirb-pprinter 1.6.0, released in March 2021, with the latest version of gtirb. There have been a few breaking changes in the last year which prevent the older gtirb-pprinter from compiling with that version of gtirb. Is building the latest version of gtirb-pprinter--1.8.2 was released on January 14, 2022--an option? You should have fewer issues building that way.

**Comment by kermitdafrog8** [comment]
Trying to build from master I get the following error plus more similar errors now:

[ 31%] Building CXX object src/gtirb_pprinter/CMakeFiles/gtirb_pprinter.dir/ArmPrettyPrinter.cpp.o
/opt/gtirb-pprinter/src/gtirb_pprinter/ArmPrettyPrinter.cpp: In lambda function:
/opt/gtirb-pprinter/src/gtirb_pprinter/ArmPrettyPrinter.cpp:393:12: error: ‘ARM_SYSREG_MSPLIM’ was not declared in this scope; did you mean ‘ARM_SYSREG_MSP’?
  393 |       case ARM_SYSREG_MSPLIM:
      |            ^~~~~~~~~~~~~~~~~
      |            ARM_SYSREG_MSP
/opt/gtirb-pprinter/src/gtirb_pprinter/ArmPrettyPrinter.cpp:396:12: error: ‘ARM_SYSREG_PSPLIM’ was not declared in this scope; did you mean ‘ARM_SYSREG_PSP’?
  396 |       case ARM_SYSREG_PSPLIM:
      |            ^~~~~~~~~~~~~~~~~
      |            ARM_SYSREG_PSP
/opt/gtirb-pprinter/src/gtirb_pprinter/ArmPrettyPrinter.cpp:399:12: error: ‘ARM_SYSREG_MSP_NS’ was not declared in this scope; did you mean ‘ARM_SYSREG_SP_USR’?
  399 |       case ARM_SYSREG_MSP_NS:
      |            ^~~~~~~~~~~~~~~~~
      |            ARM_SYSREG_SP_USR
/opt/gtirb-pprinter/src/gtirb_pprinter/ArmPrettyPrinter.cpp:402:12: error: ‘ARM_SYSREG_PSP_NS’ was not declared in this scope; did you mean ‘ARM_SYSREG_SP_USR’?
  402 |       case ARM_SYSREG_PSP_NS:

**Comment by jdorn-gt** [comment]
Those symbols are provided by GT's capstone fork. You need to check out and build the `next` branch, not the default `master` branch.

**Comment by kermitdafrog8** [comment]
GT's capstone fork version 4.0.1?

**Comment by jdorn-gt** [comment]
I'm using the "unstable" package following the instructions from here: https://github.com/grammatech/gtirb#ubuntu. It shows up as version 4.0.2-gtdev.

Or building directly from the HEAD of the `next` branch, which also has version 4.0.2.

**Comment by kermitdafrog8** [comment]
The library version I just compiled came out to be libcapstone.so.5

Is this the correct version?
