### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by R2IDefense** [GrammaTech/gtirb-pprinter#13]
It looks like a couple definitions are missing from `AuxDataSchema.hpp` for the commit that introduced `ElfDynamicInit` and `ElfDynamicFini`. 

Thanks

**Comment by aeflores** [comment]
We have moved `ElfDynamicInit` and `ElfDynamicFini` to GTIRB https://github.com/GrammaTech/gtirb/commit/05a7359249a34f3fa6888e6d7f8c64c45181a2ab, maybe you need to update GTIRB to latest?

**Comment by R2IDefense** [comment]
That is extremely odd... I synched our fork with the latest issues, did a pull, it wasn't there.  Did another pull today, and it was one of 4 files that was updated.  Sorry, not sure what happened. Thanks.
